# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- group: VSMarketplace
- name: vSMarketplacePAT
  value: $[variables._PersonalAccessToken]
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'
- name: builtVSIX
  value: 'D:\a\1\s\IntelliTect.Snippets\bin\Release\IntelliTect.Snippets.vsix'
- name: publishManifestPath
  value: 'D:\a\1\s\IntelliTect.Snippets\bin\Release\publishManifest.json'
- name: vsixPublisher
  value: 'D:\a\1\s\PublishingTools\VsixPublisher.exe'
 


steps:


- powershell: $env:vsixPublisher publish
  env:
    psMarketplacePAT: $(vSMarketplacePAT)
   
   
   
